CREATE TABLE posts(id INTEGER PRIMARY KEY,title VARCHAR(128), post TEXT);
CREATE TABLE users(id INTEGER PRIMARY KEY,fname VARCHAR(128), lname VARCHAR(128), username VARCHAR(128), password VARCHAR(128));
